include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
    always_use_package_imports: true
    always_declare_return_types: false
    type_annotate_public_apis: false
    sort_pub_dependencies: false
    avoid_setters_without_getters: false
    parameter_assignments: false
    avoid_classes_with_only_static_members: false
    directives_ordering: false
